---
config:
  look: neo
  layout: elk
---
flowchart LR
 subgraph uiContainer["Vercel"]
        webapp["WebApp"]
  end
 subgraph hfContainer["HuggingFace"]
        llmrepo["LLM"]
  end
 subgraph gpuContainer["AMD"]
        hostedllm["LLM"]
  end
 subgraph backContainer["Vultr"]
        api["Reserved IP"]
        containerrepo["Container Registry"]
        backserver["Backend Server"]
        objectstore["ObjectStore"]
        gpuContainer
  end
 subgraph mistralContainer["Mistral"]
        aivision["AI vision"]
        mistralllm["LLM"]
  end
 subgraph nosqlContainer["MongoDB"]
        nosqldb["NoSQL"]
  end
 subgraph lumaContainer["Luma"]
        txt2img["Text-To-Image"]
        txt2vid["Text-To-Video"]
  end
 subgraph s1["Picture-to-Palatable"]
        uiContainer
        backContainer
        nosqlContainer
        mistralContainer
        lumaContainer
  end
    user["User"] --> webapp
    webapp --> nosqldb & aivision & api & objectstore
    api --> backserver
    llmrepo --> hostedllm
    containerrepo --> backserver
    backserver --> hostedllm & objectstore & nosqldb & mistralllm & txt2img & txt2vid
    webapp@{ icon: "fa:building"}
    llmrepo@{ icon: "fa:address-card"}
    hostedllm@{ icon: "fa:chess-pawn"}
    api@{ icon: "fa:map"}
    containerrepo@{ icon: "fa:square-caret-right"}
    backserver@{ icon: "fa:sun"}
    objectstore@{ icon: "fa:folder-open"}
    aivision@{ icon: "fa:eye"}
    mistralllm@{ icon: "fa:chess-pawn"}
    nosqldb@{ icon: "fa:file-lines"}
    txt2img@{ icon: "fa:chess-rook"}
    txt2vid@{ icon: "fa:chess-pawn"}
    user@{ icon: "fa:circle-user"}
