version: '3.8'

services:
  frontend:
    command: npm run dev
    volumes:
      - ./front/nextjs_ts:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost/api/backend
    expose:
      - "3000"

  backend:
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./back/sample:/code
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=https://localhost
    expose:
      - "80"

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_dev_data:/data
      - caddy_dev_config:/config
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_dev_data:
  caddy_dev_config:
