version: '3.8'

services:
  frontend:
    image: ams.vultrcr.com/ptpcrtstnl001/next_ts:latest
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://199.247.26.104/api/backend
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ams.vultrcr.com/ptpcrtstnl001/backend:latest
    expose:
      - "80"
    environment:
      - CORS_ORIGINS=https://199.247.26.104
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  caddy_data:
  caddy_config:
