version: '3.8'

services:
  frontend:
    build:
      context: ./front/nextjs_ts
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://localhost/api/backend
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./back/sample
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - CORS_ORIGINS=https://localhost
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  caddy_data:
  caddy_config:
